### PR TITLE
add hitcon2017_sakura exmaple

### PR DESCRIPTION
**Pull request by Kyle-Kyle**

### CODE REVIEW

**Comment by rhelmot** [comment]
original: `python solve.py  45.95s user 0.43s system 99% cpu 46.391 total`
this PR: `python solve.py  40.89s user 0.39s system 99% cpu 41.310 total`

are you sure about that?

**Comment by rhelmot** [comment]
also some concerns about sakura:

- you need to add it to test_examples.py. probably mark it as slow
- please rewrite it to not use pwntools
- please don't ever have logging directives at the module level. they clutter up the test results, since we have to run nose with --nologcapture. Stick it in the `if __name__ == '__main__'` block

**Comment by rhelmot** [comment]
also I think I did those timings wrong the first time:

original: `python solve.py  38.36s user 0.40s system 99% cpu 38.777 total`
this PR: `python solve.py  38.25s user 0.37s system 99% cpu 38.626 total`

**Comment by Kyle-Kyle** [comment]
In terms of `angrybird` example, I think I did something wrong with timing which made me think `angr.options.unicorn` did speed up things. I have discarded that commit.

In terms of `sakura`, I have done some changes to comply what you mentioned.

BTW, maybe I ask in what situation `angr.options.unicorn` will make a huge difference. Currently, I find it broken sometimes. I tried to include that option in the solution of `sakura`, but angr just can not find any address I tell it to find if I enable that option.

**Comment by rhelmot** [comment]
Unicorn is meant to help when you have to concretely execute a ton of startup code, e.g. with an unpacker. It is designed to gracefully fall back to symbolic execution when it can no longer perform concrete execution (i.e. when symbolic data is introduced). If you have a situation where something doesn't work with unicorn but works without, open a bug. Perhaps try with `add_options=angr.options.unicorn - {angr.options.UNICORN}` to see if it's really unicorn or just your script reacting badly to some other options that were being added, notably that all memory and registers are zero-initialized instead of symbolic-initialized by default.

**Comment by rhelmot** [comment]
You also need to fix lint for your new file. See the CI logs.

**Comment by Kyle-Kyle** [comment]
BTW, I have checked the `angr.options.unicorn` issue. `add_options=angr.options.unicorn - {angr.options.UNICORN}` works fine. But `add_options=angr.options.unicorn` don't. I will create a new issue after this PR got merged.

**Pull request merged**
