### PR TITLE
Made Lesson 0

### PR DESCRIPTION
**Pull request by brendabrandy**
I made a new folder to contain all the lessons. I made lesson 0 (Getting started) and have plans to make lesson 1 (Static analysis) later on. The lessons are in the format of a jupyter notebook.

### CODE REVIEW

**Comment by zardus** [comment]
Did you forget to push the notebook?

Also, I just remembered about @P1kachu's start on this from a while back: https://github.com/angr/angr-doc/blob/master/docs/courses/step0-basic_symbol_execution.md. Do you think we can combine that step0 and your lesson0 somehow, to avoid information duplication?

**Comment by brendabrandy** [comment]
oh no you're right! I just came back a while ago -- will work on it today and tomorrow. the basic symbolic execution tutorial is definitely helpful -- thanks!

**Comment by brendabrandy** [comment]
On this topic -- I also see that you've uploaded the acsac course. Can you give me the link to the powepoint used in the presentation? It would help me layout the course.

**Comment by zardus** [comment]
We finally got around to posting the ACSAC course slides: https://docs.google.com/presentation/d/1eOOW6-roopNHg8J4DJSD1V0EWzKFHxAzFKfbyRcTt2o/edit#slide=id.p

**Pull request closed without merging**
