### PR TITLE
Example; How to solve a simple, static/stripped binary

### PR DESCRIPTION
**Pull request by FrankSpierings**
A simple example on how to use angr to solve a static/stripped binary, including how to use IDA FLiRT signatures.

### CODE REVIEW

**Comment by zardus** [comment]
Could you also push your compiled binary? You can then use the specific addresses in the docs, and make it easier to follow.

Internal note: I think it's time to split the examples into two directories, the "official" (tested, etc) examples, and "contribs", to be able to more easily merge in these sorts of examples.

**Comment by ltfish** [comment]
@rhelmot Just noticed that this PR is still open (after three years)! Do we want to take it?

**Comment by rhelmot** [comment]
This seems more like a tutorial of how to use IDA than how to use angr. shouldn't we write something using the new flirt matching support?

**Comment by ltfish** [comment]
That works for me.

@FrankSpierings Thank you for the contribution. I will close this PR in light of the recently merged FLIRT support in angr itself.

**Pull request closed without merging**
