### PR TITLE
Added Google CTF example

### PR DESCRIPTION
**Pull request by Manouchehri**

### CODE REVIEW

**Comment by ltfish** [comment]
Thanks for adding this example! I'm happy to see angr working on an unbreakable challenge :-)

Can you please add a `test` method so that our CI can pick it up and test it for all future changes in angr? Here is an example to reference: [solve.py of reversing 200, DefCamp CTF](https://github.com/angr/angr-doc/blob/master/examples/defcamp_r200/solve.py) I can certainly do it for you (if you want), but that will hurt your line numbers in angr-doc!

**Comment by Manouchehri** [comment]
Done, haven't tested it though.

**Comment by ltfish** [comment]
:-(

**Comment by ltfish** [comment]
...continued

The script raises an exception:

```python
AttributeError                            Traceback (most recent call last)
/home/fish/projects/angr-doc/examples/google2016_unbreakable/solve.py in <module>()
     51 
     52 if __name__ == '__main__':
---> 53         print(repr(main()))

/home/fish/projects/angr-doc/examples/google2016_unbreakable/solve.py in main()
     43         solution = found.state.se.any_n_str(argv1, 100)
     44         print repr(solution)
---> 45         solution = solution[:solution.find("\x00")]
     46         print solution
     47         return solution

AttributeError: 'list' object has no attribute 'find'
> /home/fish/projects/angr-doc/examples/google2016_unbreakable/solve.py(45)main()
     44         print repr(solution)
---> 45         solution = solution[:solution.find("\x00")]
     46         print solution

```

**Comment by ltfish** [comment]
Gotta go to bed. Looking forward to your updated version!

**Comment by Manouchehri** [comment]
It *should* work now.

**Comment by ltfish** [comment]
Apparently `test()` does not work, since you didn't truncate the result string: 

```
'CTF{0The1Quick2Brown3Fox4Jumped5Over6The7Lazy8Fox9}@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\x04@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

I will accept this PR, and then make some modifications accordingly.

Thanks again!

**Pull request merged**
