### PR TITLE
Added more CSCI binaries.

### PR DESCRIPTION
**Pull request by Manouchehri**
Bug fixed in https://github.com/angr/angr/issues/128.

### CODE REVIEW

**Comment by ltfish** [comment]
I'm down to take this one. Can you please write a couple of sentences in `examples.md` so search engines can find it easily?

**Comment by Manouchehri** [comment]
It's already mentioned them in examples.md, I put it down at the bottom. =)

**Comment by ltfish** [comment]
Ahhhhhh I see, sorry I was a bit confused just now. I'll merge it in.

**Comment by ltfish** [comment]
Merged. Thanks!

**Pull request merged**
