### PR TITLE
Add api documentation for `ailment`

### PR DESCRIPTION
**Pull request by Pamplemousse**
There are docstrings in the ailment project!

### CODE REVIEW

**Comment by Pamplemousse** [comment]
I am quite unsure, but it seems that `ailment.manager.Manager` class is used to help during conversions.
Should we put that under the `Converter` section in the [toctree](api-doc/source/ailment.rst)?

**Comment by Pamplemousse** [comment]
Oh, and if anyone have a clue at why this exception is raised [in the build](https://travis-ci.org/angr/angr-doc/builds/548665867)...

**Comment by rhelmot** [comment]
1) the error is caused by a dependency loop being handled non-gracefully. The reference to ailment.expressions in simenginelinght in angr should involve an `import ailment.expression` or `from ailment.expression import Const`
2) All the ailment classes should be under the ailment section
3) Ailment should ABSOLUTELY NOT be placed above angr in the table of contents

**Comment by rhelmot** [comment]
Error should be fixed with above commit

**Comment by Pamplemousse** [comment]
Did you forget to remove debugging statements, or are the `if... ipdb...` things meant to be in this commit?

**Comment by Pamplemousse** [comment]
Regarding the order of things in the TOC, it seemed that it was following an alphabetical order...

I agree with the fact that `angr` is the "most important thing" (central module), but I feel like not respecting any "natural order" in the doc would make it harder to navigate for newcomers.

**Comment by rhelmot** [comment]
forgot to remove debug statements. they're gone now.

it is not in alphabetical order. archinfo is last :P It should go in reverse dependency order, with things coming before the things they depend on. It's not super elegant for understanding, but the api docs are meant as a reference. we have the gitbook if you want to read it front to back.

**Comment by twizmwazin** [comment]
We do need to finish this, it will need to be rebased which may require a new PR.

**Comment by twizmwazin** [comment]
Closing in fabor of #418

**Pull request closed without merging**
