### PR TITLE
Added symbolic write example.

### PR DESCRIPTION
**Pull request by Manouchehri**
Taken from xoreaxeaxeax (with permission) off the mailing list.

https://lists.cs.ucsb.edu/pipermail/angr/2016-August/000171.html

### CODE REVIEW

**Comment by ltfish** [comment]
Could you add a few lines of description in `examples.md`? That'll be awesome :-)

**Comment by Manouchehri** [comment]
Yes, will do. Should probably also be mentioned in simuvex.

"Note to self: too busy right now, but it'd be cool to add that answer to
GOTCHAS.md, or maybe add a 'Symbolic Index Resolution' section to simuvex.md
."

https://lists.cs.ucsb.edu/pipermail/angr/2016-August/000170.html

**Comment by ltfish** [comment]
@zardus ^^^^^

**Comment by rhelmot** [comment]
@ltfish @zardus are we comfortable having a binary in angr-doc instead of the binaries repo? I'm fine with it, but it makes me a little nervous...

**Comment by rhelmot** [comment]
...I'm sorry. I'm being an idiot, we have tons of binaries in this repo!!! This is good and can be merged.

**Pull request merged**
