### PR TITLE
Add some easy Java samples.

### PR DESCRIPTION
**Pull request by antoniobianchi333**

### CODE REVIEW

**Comment by antoniobianchi333** [comment]
@ltfish @conand 
Do you think this can be merged?

(I also have an interesting example using Java/native I would like to merge too.)

**Comment by conand** [comment]
I see some old python2 code, we should review and test it.

**Comment by rhelmot** [comment]
Yes, these are good examples that should be merged, once they're a) fixed for py3k and b) added to test_examples

**Comment by antoniobianchi333** [comment]
Superseeded by:
https://github.com/angr/angr-doc/pull/254

**Pull request closed without merging**
