### PR TITLE
First version of angr courses - WIP

### PR DESCRIPTION
**Pull request by P1kachu**
(The only interesting files for this PR are the ones in [this commit](https://github.com/angr/angr-doc/pull/74/commits/fdb80d42e513bfb250a96d07efef334c9ad17d45))

Here is a first idea on how the angr courses could be written.
I was planning on creating a file where the explanation would NOT be in the comments of the python code, but I am not sure it would have worked with the `test.py` script.
No need to merge it right now though. Some more could be added before I think, unless you like this and want to provide a template for others.

Tell me what you think, so that I can continue or fix :)

### CODE REVIEW

**Comment by bananaappletw** [comment]
It this pr still going on?

I try to learn angr recently.

I am glad to see any tutorial that helps people to understand more about angr.

Thanks.

**Comment by P1kachu** [comment]
I am waiting for some upstream approval before going any further :)

**Comment by ltfish** [comment]
@P1kachu sorry, we didn't realize that you are waiting for feedbacks from us.

We believe having angr courses will be awesome. However, since angr is still evolving in a fast pace, online angr courses will have to be adapted constantly to the latest angr design and implementation. It'll be great if there are more people (I mean, more than just yourself) is involved in this process.

For more feedbacks, I'm _kindly poking_ @zardus :-)

**Comment by ssatanss** [comment]
Good job keep them comming :D

**Comment by zardus** [comment]
Yo! Sorry, this got buried in the CGC rush.

I think this is a great start. When one of us has a moment, we'll get it hooked into our CI (should just be a matter of adding the .md to the doc-tester) and then merge it in.

Going forward, I think it'd be very useful to have a lesson on the static analysis in angr, and how/when one would apply it. I'd be interested in learning that as well ;-)

**Comment by rhelmot** [comment]
In the future, please put fixes unrelated to the subject of a PR in a separate PR :stuck_out_tongue_winking_eye:

**Comment by rhelmot** [comment]
I added this to CI with bdd0af7!

**Pull request merged**
