### PR TITLE
Added EKOPARTY CTF 2016 Sokohash V2 Example

### PR DESCRIPTION
**Pull request by Manouchehri**
Needs a bit of work to work properly with the CI, but otherwise it looks fine to me.

### CODE REVIEW

**Comment by Manouchehri** [comment]
Anything I need to fix in this?

**Comment by rhelmot** [comment]
Looks good. Could you move the files out of the root of the `examples` folder and into their own subdirectory?

regarding the "capstone errors out in pypy" comment, we noticed this and submitted a fix to capstone. However, the version of capstone that you get via `pip install capstone` is a year and a half old. If you want the best version of capstone, install from the [github repo](https://github.com/aquynh/capstone) or from [our fork](https://github.com/angr/capstone).

**Comment by Manouchehri** [comment]
Oops, I had a `examples/ekopartyctf2016_sokohashv2/` folder locally but forgot to commit it. Thanks for pointing that out, fixed!

Paging @P0lako for the capstone comment.

**Comment by P0lako** [comment]
Thanks @Manouchehri. Do you need anything that I can add or remove or fix?

**Comment by zardus** [comment]
Okay! We merged all the crazy internal changes last night, so we're resuming PR merges :-)

For this one, two things need to be done:

1. @Manouchehri, could you rebase this on current master? That way we can have the tests re-run.
2. What's keeping this from being added to CI? Could we put everything in a `main` function, and call it from `test`?

**Comment by Manouchehri** [comment]
Done.

**Comment by zardus** [comment]
Thanks! Thoughts on the testing?

**Comment by zardus** [comment]
I added some smoketesting, to at least make sure the scripts produce expected output :-)

**Pull request merged**
