### PR TITLE
add 0ctf momo

### PR DESCRIPTION
**Pull request by ocean1**

### CODE REVIEW

**Comment by ltfish** [comment]
As we have discussed on slack, please make changes accordingly. Let me know when you are ready :-)

**Comment by ocean1** [comment]
done, do you mind if I don't put my real name there? :)

**Comment by ltfish** [comment]
@ocean1 I'm fine with whatever name you like!

**Comment by ocean1** [comment]
perfect it's ok then :) feel free to remove the test prints if you think it fits better the style of the other examples.

**Pull request merged**
