### PR TITLE
Feat/java examples

### PR DESCRIPTION
**Pull request by antoniobianchi333**
This PR adds some new sample for Java/Native, including a solver for an ictf challenge.
It also resurrects old java samples bringing them to Python3.
This PR is linked to the feat/java_examples branch in angr/angr

### CODE REVIEW

**Comment by zardus** [comment]
There are a lot of gradle files and such in here... Is that intentional?

**Comment by antoniobianchi333** [comment]
Yes, I left the files needed to compile the Android app.

**Comment by zardus** [comment]
Ah, I see. Also, could you look into the test failures? It looks like the runner isn't handling the examples properly.

**Comment by antoniobianchi333** [comment]
I am working on them right now.
(android tests are automatically skip unless you add the Android SDK to the CI, I will open a separate issue for that)

**Comment by antoniobianchi333** [comment]
Ok, CI is green

**Pull request merged**
