### PR TITLE
Added a few MBE examples.

### PR DESCRIPTION
**Pull request by Manouchehri**

### CODE REVIEW

**Comment by Manouchehri** [comment]
The reason I put some of the disassembly inline is so that people Google'ing parts of the binary will be linked here. (e.g. `Lqydolg_Sdvvzrug_`)

**Comment by zardus** [comment]
Cool stuff!

This is me thinking out loud more than as comment on the docs, but: `PathGroup.explore` can accept arbitrary functions for the `find` and `avoid` arguments. I've been thinking that we're actually kinda under-selling angr's capabilities by just seeking to an address -- we could go "higher-level" and seek to the path that prints "Correct" while avoiding the path that prints "Wrong", without knowing anything about the binary at all.

Just a thought brought on by how nice angr seems to work on these crackmes.

**Comment by Manouchehri** [comment]
@zardus You mean with the CFG? I'm doing that in [`crackme0x04`](https://github.com/Manouchehri/angr-doc/blob/55d095cfe4d9e1155793965b17c41eb48ba39402/examples/CSCI-4968-MBE/challenges/crackme0x04/solve.py#L16), but [unfortunately it's not working right now](https://github.com/angr/angr/issues/128).

```python
#!/usr/bin/env python2

# Author: David Manouchehri <manouchehri@protonmail.com>

import angr

def main():
    proj = angr.Project('crackme0x04', load_options={"auto_load_libs": False}) 

    cfg = proj.analyses.CFG()
    FIND_ADDR = cfg.kb.functions.function(name="exit").addr
    AVOID_ADDR = 0x080484fb # dword [esp] = str.Password_Incorrect__n ; [0x8048649:4]=0x73736150 LEA str.Password_Incorrect__n ; "Password Incorrect!." @ 0x8048649

    path_group = proj.factory.path_group()
    path_group.explore(find=FIND_ADDR, avoid=AVOID_ADDR)
# ...rest of function is in the repo
```

**Comment by rhelmot** [comment]
no, he means that the `find` parameter to explore can be a function itself.

```python
def is_result_state(path):
   return 'Correct' in path.state.posix.dumps(1)
def is_fail_state(path):
   return 'Wrong' in path.state.posix.dumps(1)

pg.explore(find=is_result_state, avoid=is_fail_state)
```

**Comment by Manouchehri** [comment]
Oh, that's cool. What type(s) should I be returning? True/False?

**Comment by rhelmot** [comment]
A bool. This takes about 15 seconds to find out if you look at path_group.py.

**Comment by zardus** [comment]
To be fair, that code is a tad bit convoluted and you'd need to follow it through like 10 functions :-)

**Comment by Manouchehri** [comment]
As a non-developer after looking at it for two minutes I still wouldn't have guessed that I could do that..

I'll add it to the docs once I try it on another binary.

**Comment by Manouchehri** [comment]
I won't be changing these scripts any more, I'll be using those suggestions
in the next batch of examples I do.

**Comment by salls** [comment]
Might be nice to do something like the lambdas in these examples. Ideally, there would be different capabilities/uses of angr in each example. I'm a little worried that too many of the scripts in the examples are doing the same thing. 

That being said, we'll probably merge this in either way :)

**Comment by zardus** [comment]
Hey @Manouchehri, would you mind adding some text to EXAMPLES.md to link to these guys?

**Comment by Manouchehri** [comment]
@zardus Sure. Probably makes sense to do just one link to the folder since all of the challenges are very similar?

**Comment by zardus** [comment]
Agreed; just some text and a link to the folder would be perfect.

**Comment by zardus** [comment]
This series of examples got me thinking that it'd be really cool to develop some sort of "angr class" with some progression of examples that requires progressively more advanced angr capabilities.

We should really have a list of these self-contained things that people can contribute somewhere in the docs...

**Comment by Manouchehri** [comment]
ugh fail, I should have pulled first. One second..

**Comment by Manouchehri** [comment]
Wow, that took a lot longer than it should have. Using git on a sshfs filesystem is a horrible idea. Fixed now.

@zardus Agreed, right now people tend to just start at the top of the `examples.md` list and work down; less than ideal since they don't go in order of difficulty.

**Pull request merged**
