### PR TITLE
Replaced otiegnqwvk with Exploration Technique in pipeline.md

### PR DESCRIPTION
**Pull request by Komasa**
Title pretty much says it, it's annoying to read and really has no point in being in the doc in my opinion

### CODE REVIEW

**Comment by rhelmot** [comment]
otiegnqwvk is another name for exploration technique. It is pronounced oh-tie-gin-quick. If you think it is unclear, the correct solution is to clarify that they are the same thing.

**Comment by schieb** [comment]
> it's annoying to read

> pronounced oh-tie-gin-quick

Or otie for short 😃

**Comment by zardus** [comment]
As an update: there is intense internal debate about how to approach otiegnqwvks. On the one hand, I strongly feel that projects, even big ones, should have a sense of humor. On the other hand, as you pointed out, it causes confusion. One day, we'll find the correct balance.

**Comment by LarryWaldrop** [comment]
> On the one hand, I strongly feel that projects, even big ones, should have a sense of humor. 

That's cool, having a private language is actually a natural and really positive sign of tight-knit group. It reflects positively that morale is up at shellphish HW. However, the documentation is really targeted at your *users*, isn't it? And you're actively seeking contributions from people outside the group, right? For documentation especially, right? and random folks are starting to respond and show up with contributions you like, right? so, maybe keeping the language to standard english is where things will inevitably tend towards. You can help it along or not and maybe it's just too early for you guys to accept these kind of changes. I get attached to things like that myself when I work on projects I care about. It's totally understandable.   But can we **at least merge some explanation** in the text now for people who have no idea WTH it's about? some of whom aren't native english speakers (but charming, capable individuals regardless and valuable contributors in-potentia)? 

So, please see the fix [commit](https://github.com/angr/angr-doc/pull/123/commits/152f498115c457c9330ea20e417abb389819d485) for this in #123, added about 3 hours *prior* to this very PR. Yes, that's right, yet more anecdotal evidence that this quirk annoys most everyone who reads the docs and wasn't in the room with you guys when `angr` was being written.

**Comment by rhelmot** [comment]
I sign off on this PR.

I wrote the doc this way because it bothered me to repeat the phrase "exploration technique" over and over again, and wanted to have some variance in language. The fatal assumption on my part was thinking that a) everyone would read the docs in order, and b) the otiegnqwvk name was explained earlier in the docs.

With this in mind, I think we should also amend this page to include a brief explanation of the high-level goals of an exploration technique too.

**Comment by rhelmot** [comment]
Also, I'd like to apologize for having been unable to deal with this or the linked PR earlier. I've been managing my time poorly and haven't been able to devote time to angr dev lately. Hopefully this will be fixed by Thursday.

**Comment by Komasa** [comment]
@LarryWaldrop 
I actually saw your PR, but personally thought that just explaining it isn't sufficient. I find it a bit strenuous to read the docs even when knowing that "otiegnqwvk" means Exploration Technique.

In general bit of humor in a project is great as long as it does not impede functionality.
I personally used the docs at https://docs.angr.io/ and the first mention of "otiegnqwvk" is at https://docs.angr.io/docs/pipeline.html where it is first used in "This is where an ExplorationTechnique can start to affect things. If any active otiegnqwvk has provided a step override, this is where it is called. "

**Comment by LarryWaldrop** [comment]
@rhelmot, thanks for understanding. Mnemonics are awfully useful but generally work better if they also provide some semantic hint as to their referent. Otherwise, we'd all be naming our variables using a checksum of their description, right? ;)

@Komasa , no argument here, but I also know how it can be when random people start showing up at your repo (representing tons of work) and start bitching about idiosyncrasies, so giving some leeway to the people who erected the edifice isn't a wrong approach either. That is, until the repo gets about 2k stars, and then you just have to be ruthlessly pragmatic.
 
So, seeing as @rhelmot has kindly yielded, I'm removing the explanation commit from my PR.
@Komasa, leaving it to you to add "a brief explanation of the high-level goals of an exploration technique."

**Pull request merged**
