### PR TITLE
Added example from EKOPARTY CTF 2016 (rev250)

### PR DESCRIPTION
**Pull request by docileninja**
Fixed a few typos as well

### CODE REVIEW

**Comment by docileninja** [comment]
Note that the writeup is not yet up on my website (I'm working on it now)

**Comment by docileninja** [comment]
Link is working now

**Comment by docileninja** [comment]
Bump

**Comment by zardus** [comment]
Bump received! Could add the testing of this script to test.py? That way, we can make sure that angr updates won't break this example in the future. Otherwise, it looks good!

**Comment by zardus** [comment]
Bump :-)

Also, could you rebase this on current master? We merged a lot of changes in last night, and it'd be great to make sure this is tested with the latest stuff.

**Comment by docileninja** [comment]
Everything should be good to go now

**Comment by zardus** [comment]
Erm, I did something ungood and this is mysteriously closed. Investigating...

**Comment by zardus** [comment]
Oookay, I tried to do the squash-merge on the commandline, and somehow wiped out this PR, but the commit made it into master. Here it is: https://github.com/angr/angr-doc/commit/14a427df6c636e82bd26b95d88edf5c348e55d02

Sorry it took us so long to get to merging this, and thanks for the contribution!

**Pull request closed without merging**
