### PR TITLE
added example for trace from 0ctf quals

### PR DESCRIPTION
**Pull request by WGH-**

### CODE REVIEW

**Comment by ltfish** [comment]
Thanks for writing this example, we really appreciate it :-)

Before merging it in, some changes have to be made in your script. In order for our CI to test it, there needs to be a `test()` method that checks if the output complies with the expected result. Also it would be nice to put all code in a single method (for example, `main()`). Here is an example that could be helpful: https://github.com/angr/angr-doc/blob/master/examples/ais3_crackme/solve.py

If you want, I can go ahead and make those changes. However, I figure it's better for you to do it and rebase your commit so your authorship on those lines are preserved. Let me know if you'd like me to do it!

**Comment by WGH-** [comment]
I'll do it

**Comment by WGH-** [comment]
Done!

**Comment by ltfish** [comment]
Just tested and merged. Thank a lot!

**Pull request merged**
