### PR TITLE
Chinese Translation

### PR DESCRIPTION
**Pull request by Vsane**
slover

### CODE REVIEW

**Comment by zardus** [comment]
Wow, thank you!

Could you change this to have all the translations under a `docs-cn` directory? That way we can also keep the english docs :-)

**Comment by ltfish** [comment]
This is brilliant. Thanks a lot!

**Comment by PolluxAvenger** [comment]
Thank you for your reply, we didn't notice that you have given a reply. Soon the document will be translated and we will try our best to follow the update of the master branch. After the translation completed, I will delete this PR and resubmit a new one. At the same time, I will change this to have all the translations under a `docs-cn` directory.

**Comment by ltfish** [comment]
> At the same time, I will change this to have all the translations under a docs-cn directory.

That'll be great! In the near future when I have enough motivation to write docs, I will keep the Chinese version up-to-date, too.

Thanks for your contribution!

**Pull request closed without merging**
