### PR TITLE
Added a CS Games 2018 challenge.

### PR DESCRIPTION
**Pull request by Manouchehri**
This one is a fun example since we're adding constraints _after_ finding the initial path.

### CODE REVIEW

**Comment by rhelmot** [comment]
Looks good! As you can see, CI is failing because you need to add your example to tests/test_examples.py - mark it as slow if it takes longer than 2 minutes. Thanks!

**Comment by Manouchehri** [comment]
Done, added!

**Comment by ltfish** [comment]
It failed linting. Can you please fix the linting errors?

**Comment by Manouchehri** [comment]
Done!

**Comment by zardus** [comment]
Almost there - just two more lint failures!

**Comment by rhelmot** [comment]
Looks good, thanks!

**Pull request merged**
