### PR TITLE
Angr pr

### PR DESCRIPTION
**Pull request by Mastermjr**
Hello Angr developers, 

I'm currently in Antonio Bianchi's CS527 class at Purdue and as part of my semester final project I wanted to send a pull request to add an example challenge to the "./examples" directory. I did my best to document the solution script well and give credit for the design and original solution of the challenge to the b01lers ctf team. 

Please let me know if anything else is needed  for the pull request, or changes that need to be made.

### CODE REVIEW

**Comment by antoniobianchi333** [comment]
@Mastermjr please fix the errors you get in the CI log:
https://dev.azure.com/angr/angr-doc/_build/results?buildId=2694&view=results

**Comment by Mastermjr** [comment]
My file wasn't in the suite of tests, so hopefully its ok now :)

**Comment by antoniobianchi333** [comment]
You should also fix the linting of the code.

**Comment by antoniobianchi333** [comment]
@rhelmot I think this is good to be merged.

**Comment by ltfish** [comment]
Merged. Thanks!

**Comment by rozbo** [comment]
Hi @Mastermjr , I can't find your other contact information, so I'd like to ask you two questions here. Your script works a lot, but I've been thinking about it for a long time and I can't understand two of them. If you are free, can you help me?
1. why we need mock 75*4 (rather than 75)? 
https://github.com/angr/angr-doc/blob/07b83e1a8af0a26af046c638206897d244e8d2d4/examples/b01lersctf2020_little_engine/solve.py#L18
the source code said
```c++
	for (size_t i = 0, j = 0; j < cmp.size(); i++, j += 4) {
		if (cmp.at(j) != s.at(i)) return false;
	}
```
the cmp.size == 300, so the MAX i= 74, means the stdin we used to this max length is 75, and with the first char , I think we just need mock 76 bytes. (but this is wrong, I know). why we should 75*4 ?

2. why we need set range step 2 to range ?

https://github.com/angr/angr-doc/blob/07b83e1a8af0a26af046c638206897d244e8d2d4/examples/b01lersctf2020_little_engine/solve.py#L59


thanks again

**Pull request merged**
