### PR TITLE
added solutions for levels 4,5,6 to cmu binary bomb

### PR DESCRIPTION
**Pull request by ocean1**
Added solutions for other 3 levels of the binary bomb (secret level left out).
Shows different ways to do things.

### CODE REVIEW

**Comment by ocean1** [comment]
seems like the failed checks do not depend on this pull req.

**Comment by zardus** [comment]
Yeap, looks like an angr-doc specific problem, because we try to get test coverage even though angr-doc isn't an actual module. Lemme see if I can figure it out.

**Comment by zardus** [comment]
Let's live dangerously ;-)

Thanks, man!

**Comment by rhelmot** [comment]
This seems to be causing intermittent failures on CI. flag 6 seems to be failing its assertion with about 50% probability. I'm going to disable that test until this is taken care of.

**Comment by rhelmot** [comment]
Oh, whoops, looks like the errors are actually coming from the secret stage, which is a different PR. the debug messages were a little misleading.

**Comment by rhelmot** [comment]
...aaaaand it looks like stage 6 is now timing out: https://travis-ci.org/angr/angr-doc/builds/188185344

**Comment by rhelmot** [comment]
................................aaaaaaaaaaand your stage 6 solution was totally wrong, returned the wrong answer.

Not only that, but the stage 5 solution was nondeterministic, since the binary was acting case-insensitively. So the CI was failing on that in a lot of cases.

I fixed both of these, and disabled stages 4 and 6 during CI because they took a really long time and didn't test anything interesting.

**Pull request merged**
